---
title: Papa Rap
baseurl: "/"
permalink: "/:title/"
palette: red
header:
  title: Papa Rap
  tagline: ''
  logo_img: "/images/logo-2.png"
  bg_img: "/images/1-1.jpg"
  has_nav: true
  has_social: true
footer:
  content: "&copy; 2019 PR Productions, LLC. All rights reserved."
  links:
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
